*Relembrando...*

Arredondamento no R de números do tipo `x.5` depende da paridade da unidade de x.

### Sistemas Lineares (cap 8.1 + 8.2)

---

Lidamos com problemas do tipo, $Ax = B$, onde $A$, uma matriz, e $b$, um vetor, são dados.


##### [Eliminação Gaussiana](https://en.wikipedia.org/wiki/Gaussian_elimination#Computational-efficiency), $O(n^3)$

#### Método de Jacobi

Decompomos a matriz $A$ na forma $L + D + U$, onde $L$ é uma matriz triangular inferior, $D$ é diagonal e $U$ é triangular superior.

Logo, ficamos com: 

$\begin{eqnarray}
(L + D + U)x & = & b \\
Dx & = & b - (L + U)x \\
x_{k+1} & = & D^{-1}(b-(L+U)v_{k})
\end{eqnarray}$ 

Solução é um ponto fixo da iteração de $v_{k}$

**Exercício 1**: 

Gere uma matriz quadrada $n\times n$ esparsa com $\approx 2\%$ das entradas diferentes de zero e menores que 1

A diagonal deve conter números aleatórios em $[\frac{4n}{100}, \frac{8n}{100}]$, para $n=10000$.

In [107]:
n = 10000

In [108]:
import numpy as np

def esparse_matrix(n):
    
    # gerando a matriz com aprox. 5% de entradas diferentes de 1
    M = np.random.rand(n,n)
    M = M * (M > 0.95).astype(int)
    
    # preenchendo a diagonal
    np.fill_diagonal(M, 0)
    d = np.diag(np.random.uniform(n*4/100,n*8/100, n))
    
    return M + d

In [109]:
%%time
A = esparse_matrix(n)

CPU times: user 2.79 s, sys: 2.17 s, total: 4.96 s
Wall time: 4.96 s


In [110]:
A

array([[722.78966196,   0.        ,   0.        , ...,   0.        ,
          0.95646311,   0.        ],
       [  0.        , 502.10943048,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        , 537.91955596, ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [  0.        ,   0.        ,   0.        , ..., 668.23295556,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.95891897, ...,   0.        ,
        487.04865982,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        , 418.24092562]])

**Exercício 2**: 

Gere um vetor aleatório $x$ e calcule $b=Ax$

In [113]:
x = 2*np.ones(n)
x.shape

(10000,)

In [114]:
x

array([2., 2., 2., ..., 2., 2., 2.])

In [115]:
b = np.inner(A,x)
b.shape

(10000,)

In [116]:
b

array([2415.42205362, 1937.39250758, 2078.73979248, ..., 2323.03334162,
       2028.82331771, 1789.22730522])

**Exercício 3**: 

Desenvolva $Ax=b$ por escalonamento e por Jacobi e compare os tempos

In [158]:
def Jacobi(A, b, x, threshold):
    
    """
    Resolove o sistema linear pelo método de Jacobi.
    
    :param A: matriz nxn
    :param b: vetor nx1
    :param x: vetor inicial
    :param threshold: número máximo de iterações
    
    :returns: vetor solução do sistema, número de iterações
    """
    
    U = np.triu(A)
    np.fill_diagonal(U, 0)
    
    L = np.tril(A)
    np.fill_diagonal(L, 0)
    
    D = np.diag(np.diag(A))
    D_inv = np.linalg.inv(D) 
    
    t = 0
    while t < threshold:
        
        x = np.inner(D_inv, b - np.inner((L+U), x))
        t += 1
    
    return x, t

In [179]:
x0 = np.ones(n)
t_max = 200

In [181]:
%%time

x, t = Jacobi(A, b, x0, t_max)

CPU times: user 35min 4s, sys: 13min 4s, total: 48min 8s
Wall time: 4min 37s


In [182]:
x

array([2., 2., 2., ..., 2., 2., 2.])

### Fazer o resto aqui!

In [ ]:
def elim_Gaussiana(A, b):

#### Exercício 4:
Exiba uma matriz onde o método de Jacobi não converge

#### Exercício 5:
    
Mostre que se a matriz A é diagonal dominanteentãoo método de Jacobi converge